# Generated by Django 3.1.7 on 2021-03-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('hid', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
