# Generated by Django 3.1.7 on 2021-03-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210321_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='count',
            field=models.CharField(default='', max_length=10),
        ),
    ]
